
server:
  port: 80
  servlet:
    context-path: /app

spring:
  mvc:
    servlet:
      load-on-startup: 0
  banner:
    location: banner.txt
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Cc@981208
    url: jdbc:mysql://localhost:3306/forum?useUnicode=true&characterEncoding=utf8


mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: ca.geer.domain
  config-location: classpath:mybatis-config.xml
#  configuration:
#    map-underscore-to-camel-case: true
#    use-generated-keys: true




